#Get plain text names of the BCO-DMO Parameters from the NERC Vocabulary Server
# @title BCO-DMO parameters named from the NERC Vocabulary Server
# @tag federated
# @tag BCO-DMO
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX bcodmo: <http://escience.rpi.edu/ontology/BCO-DMO/bcodmo/3/0/>
select ?a ?d where
{SERVICE <http://escience.rpi.edu/endpoint/sparql/>
{?a ?b bcodmo:Parameter.?a ?b ?c}
?c skos:prefLabel ?d}
LIMIT 10000