#Retrieve a given concept collection
# @title Get a concept collection
# @tag api
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?s ?o ?p WHERE {
	{
		BIND (<http://vocab.nerc.ac.uk/collection/P03/current/> as ?s)
		?s rdf:type skos:Collection.
		?s  ?o ?p
	} UNION {
		BIND (<http://vocab.nerc.ac.uk/collection/P03/current/> as ?a)
		BIND (skos:prefLabel as ?o)
		?a skos:member ?s.
		?s ?o ?p
	}
}
