#Return all triples for a given SKOS concept
# @title Get a concept
# @tag api
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?s ?o ?p WHERE {
	BIND (<http://vocab.nerc.ac.uk/collection/P03/current/D005/> as ?s)
	?s rdf:type skos:Concept.
    ?s ?o ?p
}
