#Retrieve a given concept collection
# @title Get a concept collection
# @tag api
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?o ?p WHERE {<http://vocab.nerc.ac.uk/collection/P03/current/> rdf:type skos:Collection.
                    <http://vocab.nerc.ac.uk/collection/P03/current/>  ?o ?p}