#A query to discover all of the concept schemes on the NERC Vocabulary Server
# @title What concept schemes
# @api
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?s ?o WHERE {?s rdf:type skos:ConceptScheme.
                    ?s dc:title ?o}