#Return the top concepts for a given SKOS concept scheme
# @title Get the top concepts of a given concept scheme
# @tag api
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?o WHERE {<http://vocab.nerc.ac.uk/scheme/NETMAR_OCEAN/current/> skos:hasTopConcept ?o}